services:
  - type: web
    name: mon-site-laravel
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: Dockerfile
    buildFilter:
      paths: 
        - "*"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://mon-site-laravel.onrender.com
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /tmp/database.sqlite
